---
campfire_subdomain: <%= ENV['CAMPFIRE_SUBDOMAIN'] %>

jabber_user:
  jid:      <%= ENV['JABBER_JID'] %>
  password: <%= ENV['JABBER_PASS'] %>
  server:   <%= ENV['JABBER_SERVER'] %>

users:
  -
    jid:            <%= ENV['USER1_JID'] %>
    campfire_token: <%= ENV['USER1_CAMPFIRE'] %>

log:
  stream: stderr
  level: <%= ENV['LOG_LEVEL'] %>
